### ISSUE TITLE
Ajuste de la DB para generar carrito de compras

### ISSUE THREAD

**Issue by fherevans** [kebblar/petstore-back#161]
Propuesta de tablas a anexar a la base actual

**Comment by lixleal** [comment]
Adjunto script para soportar una lista de anuncios en la misma orden de compra. Favor de validar. 

delete from orden_compra;
DROP TABLE IF EXISTS `carrito`;
DROP TABLE IF EXISTS `orden_compra`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `orden_compra` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Atributo que representa el identificador de la orden de compra',
  `id_usuario` int(11) NOT NULL COMMENT 'Atributo que representa el identificador del usuario asociado a la compra',
  `id_direccion_envio` int(11) NOT NULL COMMENT 'Atributo que representa la direccion a donde se enviar la mascota',
  `id_paqueteria` int(11) NOT NULL COMMENT 'Atributo que representa el identificador de la paqueteria asociada a la compra',
  `id_metodo_pago` int(11) NOT NULL COMMENT 'Atributo que representa el identificador del mtodo de pago asociada a la compra',
  `id_moneda` int(11) NOT NULL COMMENT 'Atributo que representa el tipo de moneda involucrada en la compra, por ejemplo, pesos, dlllares, etc.',
  `cve_orden_compra` varchar(20) NOT NULL COMMENT 'Atributo que representa la clave alfanumerica que identifica de manera univoca a la orden de compra',
  `importe_total` decimal(10,2) NOT NULL COMMENT 'Atributo que representa el importe total, es decir, costo de la mascota + costo de paqueteria',
  `fecha_hora_comprar` date NOT NULL COMMENT 'Atributo que representa la fecha y hora en que se realiza la comprar',
  `estado_envio` tinyint(1) NOT NULL COMMENT 'Atributo que representa el estado del envio, los valores validos son 1-En preparacion, 2-En camino, 3-Entregado',
  `recibo` varchar(256) NOT NULL COMMENT 'Atributo que representa el nombre del archivo con el recibo de comprar en pdf',
  PRIMARY KEY (`id`),
  KEY `fk_orden_compra_usuario` (`id_usuario`),
  KEY `fk_orden_compra_direccion_envio` (`id_direccion_envio`),
  KEY `fk_orden_compra_paqueteria` (`id_paqueteria`),
  KEY `fk_orden_compra_metodo_pago` (`id_metodo_pago`),
  KEY `fk_orden_compra_moneda` (`id_moneda`),
  CONSTRAINT `fk_orden_compra_direccion_envio` FOREIGN KEY (`id_direccion_envio`) REFERENCES `direccion` (`id`),
  CONSTRAINT `fk_orden_compra_metodo_pago` FOREIGN KEY (`id_metodo_pago`) REFERENCES `metodo_pago` (`id`),
  CONSTRAINT `fk_orden_compra_moneda` FOREIGN KEY (`id_moneda`) REFERENCES `moneda` (`id`),
  CONSTRAINT `fk_orden_compra_paqueteria` FOREIGN KEY (`id_paqueteria`) REFERENCES `paqueteria` (`id`),
  CONSTRAINT `fk_orden_compra_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `usuario` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `carrito` (
  `id_anuncio` int(11) NOT NULL COMMENT 'Atributo que representa el identificador del anuncio asociado al carrito de la orden de compra',
  `id_orden_compra` int(11) NOT NULL COMMENT 'Atributo que representa el identificador de la orden de compra',
  PRIMARY KEY (`id_anuncio`,`id_orden_compra`),
  KEY `fk_carrito_anuncio` (`id_anuncio`),
  KEY `fk_carrito_orden_compra` (`id_orden_compra`),
  CONSTRAINT `fk_carrito_anuncio` FOREIGN KEY (`id_anuncio`) REFERENCES `anuncio` (`id`),
  CONSTRAINT `fk_carrito_orden_compra` FOREIGN KEY (`id_orden_compra`) REFERENCES `orden_compra` (`id`)
);
<img width="910" alt="Captura de Pantalla 2021-06-04 a la(s) 21 05 12" src="https://user-images.githubusercontent.com/80270774/120876805-9155d180-c578-11eb-9fc3-2dd396757400.png">

**Comment by fherevans** [comment]
tengo una inquietud, al momento de recuperar el carrito deberiamos saber cual es el que est'a activo en ese momento, es decir, el que no se ha comprado a'un para que ah'i se inserten los nuevos productos
Qu'e opinan anadir a la trabla carrito la columna "ACTIVO" con un valor booleano, as'i solamente recuperamos los datos del carrito activo

**Comment by lixleal** [comment]
Se agrega atributo activo a tabla carrito. Favor de considerar actualizar el atributo posterior a finalizar cada compra.

CREATE TABLE carrito (
id int(11) NOT NULL AUTO_INCREMENT COMMENT 'Atributo que representa el identificador de un carrito de compras',
id_usuario int(11) NOT NULL COMMENT 'Atributo que representa el identificador del usuario dueño del carrito de compras',
activo tinyint(1) NOT NULL COMMENT 'Atributo que representa si el carrito está o no activo',
PRIMARY KEY (id),
KEY fk_carrito_usuario (id_usuario),
CONSTRAINT fk_carrito_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id)
);

**Comment by fherevans** [comment]
@arellano-gustavo

**Comment by lixleal** [comment]
Se ajustan las tablas de acuerdo a las recomendaciones de Gus.

delete from orden_compra;
DROP TABLE IF EXISTS `orden_compra`;
DROP TABLE IF EXISTS `carrito_anuncio`;
DROP TABLE IF EXISTS `carrito`;

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `orden_compra` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Atributo que representa el identificador de la orden de compra',
  `id_usuario` int(11) NOT NULL COMMENT 'Atributo que representa el identificador del usuario asociado a la compra',
  `id_direccion_envio` int(11) NOT NULL COMMENT 'Atributo que representa la direccion a donde se enviar la mascota',
  `id_paqueteria` int(11) NOT NULL COMMENT 'Atributo que representa el identificador de la paqueteria asociada a la compra',
  `id_metodo_pago` int(11) NOT NULL COMMENT 'Atributo que representa el identificador del mtodo de pago asociada a la compra',
  `id_moneda` int(11) NOT NULL COMMENT 'Atributo que representa el tipo de moneda involucrada en la compra, por ejemplo, pesos, dolares, etc.',
  `cve_orden_compra` varchar(20) NOT NULL COMMENT 'Atributo que representa la clave alfanumrica que identifica de manera univoca a la orden de compra',
  `importe_total` decimal(10,2) NOT NULL COMMENT 'Atributo que representa el importe total, es decir, costo de la mascota + costo de paqueteria',
  `fecha_hora_comprar` date NOT NULL COMMENT 'Atributo que representa la fecha y hora en que se realiza la comprar',
  `estado_envio` tinyint(1) NOT NULL COMMENT 'Atributo que representa el estado del envio, los valores validos son 1-En preparacion, 2-En camino, 3-Entregado',
  `recibo` varchar(256) NOT NULL COMMENT 'Atributo que representa el nombre del archivo con el recibo de comprar en pdf',
  PRIMARY KEY (`id`),
  KEY `fk_orden_compra_usuario` (`id_usuario`),
  KEY `fk_orden_compra_direccion_envio` (`id_direccion_envio`),
  KEY `fk_orden_compra_paqueteria` (`id_paqueteria`),
  KEY `fk_orden_compra_metodo_pago` (`id_metodo_pago`),
  KEY `fk_orden_compra_moneda` (`id_moneda`),
  CONSTRAINT `fk_orden_compra_direccion_envio` FOREIGN KEY (`id_direccion_envio`) REFERENCES `direccion` (`id`),
  CONSTRAINT `fk_orden_compra_metodo_pago` FOREIGN KEY (`id_metodo_pago`) REFERENCES `metodo_pago` (`id`),
  CONSTRAINT `fk_orden_compra_moneda` FOREIGN KEY (`id_moneda`) REFERENCES `moneda` (`id`),
  CONSTRAINT `fk_orden_compra_paqueteria` FOREIGN KEY (`id_paqueteria`) REFERENCES `paqueteria` (`id`),
  CONSTRAINT `fk_orden_compra_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `usuario` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `carrito` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Atributo que representa el identificador de un carrito de compras',
  `id_usuario` int(11) NOT NULL COMMENT 'Atributo que representa el identificador del usuario dueño del carrito de compras',
  `id_anuncio` int(11) NOT NULL COMMENT 'Atributo que representa el identificador del anuncio asociado al carrito',
  `id_orden_compra` int(11) NULL COMMENT 'Atributo que representa el identificador de una orden de compra',
  PRIMARY KEY (`id`),
  KEY `fk_carrito_usuario` (`id_usuario`),
  KEY `fk_carrito_anuncio` (`id_anuncio`),
  KEY `fk_carrito_orden_compra` (`id_orden_compra`),
  CONSTRAINT `fk_carrito_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `usuario` (`id`),
  CONSTRAINT `fk_carrito_anuncio` FOREIGN KEY (`id_anuncio`) REFERENCES `anuncio` (`id`),
  CONSTRAINT `fk_carrito_orden_compra` FOREIGN KEY (`id_orden_compra`) REFERENCES `orden_compra` (`id`)
);

![image](https://user-images.githubusercontent.com/80270774/121208234-87b1bf80-c83f-11eb-8cf1-771137cea329.png)

**Comment by fherevans** [comment]
id_orden_compra debe ser varchar(20) para no generar error con cve_orden_compra de la tabla de OrdenCompra.
Quedaría así:

CREATE TABLE carrito (
id int(11) NOT NULL AUTO_INCREMENT COMMENT 'Atributo que representa el identificador de un carrito de compras',
id_usuario int(11) NOT NULL COMMENT 'Atributo que representa el identificador del usuario dueño del carrito de compras',
id_anuncio int(11) NOT NULL COMMENT 'Atributo que representa el identificador del anuncio asociado al carrito',
id_orden_compra varchar(20) NULL COMMENT 'Atributo que representa el identificador de una orden de compra',
PRIMARY KEY (id),
KEY fk_carrito_usuario (id_usuario),
KEY fk_carrito_anuncio (id_anuncio),
KEY fk_carrito_orden_compra (id_orden_compra),
CONSTRAINT fk_carrito_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id),
CONSTRAINT fk_carrito_anuncio FOREIGN KEY (id_anuncio) REFERENCES anuncio (id),
CONSTRAINT fk_carrito_orden_compra FOREIGN KEY (id_orden_compra) REFERENCES orden_compra (id)
);
